# 6 LayerNorm

[**LayerNorm:**](https://docs.pytorch.org/docs/stable/generated/torch.nn.LayerNorm.html) $\;$ capa que estandariza cada dato en su última dimensión. Por ejemplo, para un tensor bidimensional:

$$
\operatorname{LayerNorm}(x_{ni}) = w_i \frac{x_{ni} - \hat{\mu}_n}{\hat{\sigma}_n} + b_i 
$$

donde $\hat{\mu}_n$ y $\hat{\sigma}_n$ son la media y desviación típica, respectivamente, calculadas en su última dimensión.

**Ejemplo** ($w_i=1$ y $b_i=0$): $$X=\begin{pmatrix}0.0415&2.2411\\1.2927&-0.6469\\0.9508&0.8249\end{pmatrix} \; \text{with} \;
\begin{bmatrix}
\hat{\mu}_1=1.1413&\hat{\sigma}_1=1.5553\\%
\hat{\mu}_2=0.3229&\hat{\sigma}_2=1.3715\\%
\hat{\mu}_3=0.8879&\hat{\sigma}_3=0.0890%
\end{bmatrix}
\;\to\;%
\operatorname{LayerNorm}(X)%
=\begin{pmatrix}-0.7071&0.7071\\0.7071&-0.7071\\0.7070&-0.7070\end{pmatrix}$$

In [1]:
import torch; import torch.nn as nn; torch.manual_seed(23)
import import_ipynb; from at251 import create_model
model = create_model(src_vocab_size=3, tgt_vocab_size=3, embed_dim=2, num_layers=1, num_heads=1, dropout=0.)

In [2]:
src = torch.LongTensor([[1, 2, 1]]); src_embedded = model.src_embed(src).data; src_embedded.data

tensor([[[ 0.0415,  2.2411],
         [ 1.2927, -0.6469],
         [ 0.9508,  0.8249]]])

In [3]:
mean = src_embedded.mean(-1, keepdim=True); print(str(mean).replace('\n', ''))
std = src_embedded.std(-1, keepdim=True); print(str(std).replace('\n', ''))

tensor([[[1.1413],         [0.3229],         [0.8878]]])
tensor([[[1.5553],         [1.3715],         [0.0890]]])


In [4]:
model.encoder.layers[0].norm_self_attn(src_embedded).data

tensor([[[-0.7071,  0.7071],
         [ 0.7071, -0.7071],
         [ 0.7070, -0.7070]]])