# 7 Residual connections

**Add:** $\;$ layer that residualizes the output of a previous layer (to facilitate the training of very deep models)

$$\operatorname{Add}(X,\operatorname{Layer}(X))=X+\operatorname{Layer}(X)$$

**Example:** $ \;$ with $\;X=\begin{pmatrix}0.0415&2.2411\\1.2927&-0.6469\\0.9508&0.8249\end{pmatrix}\;$ and 
$\;\operatorname{Layer}(X)=\begin{pmatrix}0.1616&0.3229\\0.1214&0.3137\\0.1214&0.3137\end{pmatrix}$

$$\operatorname{Add}(X,\operatorname{Layer}(X))=\begin{pmatrix}0.0415&2.2411\\1.2927&-0.6469\\0.9508&0.8249\end{pmatrix}
+\begin{pmatrix}0.1616&0.3229\\0.1214&0.3137\\0.1214&0.3137\end{pmatrix}%
=\begin{pmatrix}0.2031&2.5640\\1.4141&-0.3332\\1.0722&1.1386\end{pmatrix}$$

In [1]:
import torch; import torch.nn as nn; torch.manual_seed(23)
import import_ipynb; from at251 import create_model
model = create_model(src_vocab_size=3, tgt_vocab_size=3, embed_dim=2, num_layers=1, num_heads=1, dropout=0.)
src = torch.LongTensor([[1, 2, 1]]); x = model.src_embed(src).data; print(x)
norm_x = model.encoder.layers[0].norm_self_attn(x).data
layer_x = model.encoder.layers[0].self_attn(norm_x, norm_x, norm_x).data; print(layer_x)
print(x+layer_x)

tensor([[[ 0.0415,  2.2411],
         [ 1.2927, -0.6469],
         [ 0.9508,  0.8249]]])
tensor([[[0.1616, 0.3229],
         [0.1214, 0.3137],
         [0.1214, 0.3137]]])
tensor([[[ 0.2031,  2.5640],
         [ 1.4141, -0.3332],
         [ 1.0722,  1.1386]]])



<p style="page-break-after:always;"></p>
