# 11 Encoder

**Auto-atención:** $\quad$ $\operatorname{SelfAttention}(X)=\operatorname{MultiHead}(X,X,X)$

**Capa encoder:** $\;$ dada una secuencia de entrada $\,X=X^{(1)}\in\mathbb{R}^{n\times d_{\text{model}}},\,$ aplica
$$\begin{align*}
X^{(2)}&=\operatorname{LayerNorm}(X^{(1)})\\
X^{(3)}&=\operatorname{SelfAttention}(X^{(2)})\\
X^{(4)}&=\operatorname{Dropout}(X^{(3)})\\
X^{(5)}&=\operatorname{Add}(X^{(1)},X^{(4)})\\
X^{(6)}&=\operatorname{LayerNorm}(X^{(5)})\\
X^{(7)}&=\operatorname{PWFFN}(X^{(6)})\\
X^{(8)}&=\operatorname{Dropout}(X^{(7)})\\
\operatorname{EncoderLayer}(X)=X^{(9)}&=\operatorname{Add}(X^{(5)},X^{(8)})
\end{align*}$$


**Pre-norm vs post-norm:** $\;$ LayerNorm primero (pre-norm; arriba) o tras Add (post-norm; versión original)

**Encoder:** $\;$ dada una secuencia de entrada $\,X=X^{(1)}\in\mathbb{R}^{n\times d_{\text{model}}},\,$ aplica una pila de $N=6$ capas encoder idénticas
$$\begin{align*}
X^{(2)}&=\operatorname{EncoderLayer}(X^{(1)})\\
X^{(3)}&=\operatorname{EncoderLayer}(X^{(2)})\\
\vdots\\
X^{(N+1)}&=\operatorname{EncoderLayer}(X^{(N)})\\
\operatorname{Encoder}(X)&=\operatorname{LayerNorm}(X^{(N+1)})
\end{align*}$$



<p style="page-break-after:always;"></p>


**Ejemplo:** $\;$ $\operatorname{Encoder}(X)\,$ de una capa con la entrada y parámetros vistos anteriormente
$$\begin{align*}
X^{(2)}&=\operatorname{LayerNorm}(X^{(1)})=\begin{pmatrix}-0.7071&0.7071\\0.7071&-0.7071\\0.7070&-0.7070\end{pmatrix}\\
X^{(3)}&=\operatorname{SelfAttention}(X^{(2)})=\begin{pmatrix}0.1616&0.3229\\0.1214&0.3137\\0.1214&0.3137\end{pmatrix}\\
X^{(5)}&=\operatorname{Add}(X^{(1)},X^{(3)})=\begin{pmatrix}0.2031&2.5640\\1.4141&-0.3332\\1.0722&1.1386\end{pmatrix}\\
X^{(6)}&=\operatorname{LayerNorm}(X^{(5)})=\begin{pmatrix}-0.7071&0.7071\\0.7071&-0.7071\\0.7070&-0.7070\end{pmatrix}\\
X^{(7)}&=\operatorname{PWFFN}(X^{(6)})=\begin{pmatrix}0.2896&-0.1471\\1.0716&0.3682\\0.2896&-0.1470\end{pmatrix}\\
X^{(9)}&=\operatorname{Add}(X^{(5)},X^{(7)})=\begin{pmatrix}0.4927&2.4170\\2.4857&0.0350\\1.3618&0.9916\end{pmatrix}\\
\operatorname{Encoder}(X)&=\operatorname{LayerNorm}(X^{(9)})=\begin{pmatrix}-0.7071&0.7071\\0.7071&-0.7071\\0.7071&-0.7071\end{pmatrix}
\end{align*}$$


<p style="page-break-after:always;"></p>


In [1]:
import torch; import torch.nn as nn; torch.manual_seed(23)
import import_ipynb; from at251 import create_model
model = create_model(src_vocab_size=3, tgt_vocab_size=3, embed_dim=2, num_layers=1, num_heads=1, dropout=0.)
src = torch.LongTensor([[1, 2, 1]])
x1 = model.src_embed(src).data
x2 = model.encoder.layers[0].norm_self_attn(x1).data
x3 = model.encoder.layers[0].self_attn(x2, x2, x2).data
x5 = x1 + x3
x6 = model.encoder.layers[0].norm_ff(x5)
x7 = model.encoder.layers[0].ff(x6).data; print(x7)
x9 = x5 + x7; print(x9)
print(model.encoder.layers[0](x1, None).data)
print(model.encoder.norm(x9).data)
print(model.encode(src, None).data)

tensor([[[ 0.2896, -0.1471],
         [ 1.0716,  0.3682],
         [ 0.2896, -0.1470]]])
tensor([[[0.4927, 2.4170],
         [2.4857, 0.0350],
         [1.3618, 0.9916]]])
tensor([[[0.4927, 2.4170],
         [2.4857, 0.0350],
         [1.3618, 0.9916]]])
tensor([[[-0.7071,  0.7071],
         [ 0.7071, -0.7071],
         [ 0.7071, -0.7071]]])
tensor([[[-0.7071,  0.7071],
         [ 0.7071, -0.7071],
         [ 0.7071, -0.7071]]])



<p style="page-break-after:always;"></p>
