# 3 Convolutional layers

**Valid convolution:** $\;$ $\mathbf{Y}=\mathbf{W}\circledast\mathbf{X},\;$ with a filter $\,\mathbf{W}\;f_h\times f_w\,$ of an image $\,\mathbf{X}\;x_h\times x_w$

$$\mathbf{Y}=\begin{bmatrix}w_{0,0}&\cdots&w_{0,f_w-1}\\\vdots&\ddots&\vdots\\ w_{f_h-1,0}&\cdots&w_{f_h-1,f_w-1}\end{bmatrix}\circledast%
\begin{bmatrix}x_{0,0}&\cdots&x_{0,x_w-1}\\\vdots&\ddots&\vdots\\ x_{x_h-1,0}&\cdots&x_{x_h-1,x_w-1}\end{bmatrix}%
=\begin{bmatrix}y_{0,0}&\cdots&y_{0,y_w-1}\\\vdots&\ddots&\vdots\\ y_{y_h-1,0}&\cdots&y_{y_h-1,y_w-1}\end{bmatrix}$$

$$y_{ij}=\sum_{u=0}^{f_h-1}\sum_{v=0}^{f_w-1}w_{u,v}\,x_{i+u,j+v}\qquad\begin{gather*}
i=0,\dotsc,y_h-1\qquad y_h=x_h-f_h+1\\
j=0,\dotsc,y_w-1\qquad y_w=x_w-f_w+1
\end{gather*}$$

**Example:** $\;$ $f_h=f_w=2,\,x_h=x_w=3,\,$ so $\,y_h=y_w=2$

$$\begin{bmatrix}w_{00}&w_{01}\\w_{10}&w_{11}\end{bmatrix}\circledast%
\begin{bmatrix}x_{00}&x_{01}&x_{02}\\x_{10}&x_{11}&x_{12}\\x_{20}&x_{21}&x_{22}\end{bmatrix}
=\begin{bmatrix}y_{00}&y_{01}\\y_{10}&y_{11}\end{bmatrix}
\qquad%
\begin{align*}
y_{00}&=w_{00}x_{00}+w_{01}x_{01}+w_{10}x_{10}+w_{11}x_{11}\\[-1mm]
y_{01}&=w_{00}x_{01}+w_{01}x_{02}+w_{10}x_{11}+w_{11}x_{12}\\[-1mm]
y_{10}&=w_{00}x_{10}+w_{01}x_{11}+w_{10}x_{20}+w_{11}x_{21}\\[-1mm]
y_{11}&=w_{00}x_{11}+w_{01}x_{12}+w_{10}x_{21}+w_{11}x_{22}
\end{align*}$$

$$\begin{bmatrix}1&1\\1&1\end{bmatrix}\circledast\begin{bmatrix}1&1&0\\0&1&0\\0&1&1\end{bmatrix}
=\begin{bmatrix}3&2\\2&3\end{bmatrix}$$

In [1]:
import numpy as np; import torch 
W = torch.nn.Conv2d(1, 1, 2, bias=False)
W.weight.data = torch.tensor([[ [[1.,1.], [1.,1.]] ]], requires_grad=True)
X = torch.tensor([[ [[1,1,0], [0,1,0], [0,1,1]] ]], dtype=torch.float)
print(str(W(X).data).replace('\n',''))

tensor([[[[3., 2.],          [2., 3.]]]])



<p style="page-break-after:always;"></p>


**Zero-padding:** $\;$ zero padding $\,2\,p_h\times 2\,p_w,\,$ so $\,y_h=(x_h+2p_h-f_h+1)\,$ and $\,y_w=(x_w+2p_w-f_w+1)$

**Same convolution:** $\;$ zero-padding with $\,2p_h=f_h-1\,$ and $\,2p_w=f_w-1\,$ to preserve the input size

**Example:** $\;$ $f_h=f_w=3,\,x_h=x_w=3,\,p_h=p_w=1$ so $\,y_h=y_w=3$

$$\begin{bmatrix}1&1&1\\1&1&1\\1&1&1\end{bmatrix}\circledast\begin{bmatrix}0&0&0&0&0\\0&1&1&0&0\\0&0&1&0&0\\0&0&1&1&0\\0&0&0&0&0\end{bmatrix}
=\begin{bmatrix}3&3&2\\4&5&4\\2&3&3\end{bmatrix}$$

In [2]:
W = torch.nn.Conv2d(1, 1, 2, padding='same', bias=False)
W.weight.data = torch.tensor([[ [[1.,1.,1.], [1.,1.,1.], [1.,1.,1.]] ]], requires_grad=True)
X = torch.tensor([ [[[1,1,0], [0,1,0], [0,1,1]] ]], dtype=torch.float)
print(str(W(X).data).replace('\n',''))

tensor([[[[3., 3., 2.],          [4., 5., 4.],          [2., 3., 3.]]]])


**Strided convolution:** $\,$ to jumps $\,s_h\,$ and $\,s_w,\,$ then $\displaystyle\,y_h=\left\lfloor\frac{x_h+2p_h-f_h+s_h}{s_h}\right\rfloor\,$ e $\displaystyle\,y_w=\left\lfloor\frac{x_w+2p_w-f_w+s_w}{s_w}\right\rfloor$

**Example:** $\;$ $f_h=f_w=2,\,x_h=2,\,x_w=6,\,p_h=p_w=0,\,s_h=s_w=2,\,$ so $\,y_h=1\,$ and $\,y_w=3$

$$\begin{bmatrix}1&1\\1&1\end{bmatrix}\circledast\begin{bmatrix}1&1&0&1&0&0\\0&1&0&0&1&1\end{bmatrix}=\begin{bmatrix}3&1&2\end{bmatrix}$$

In [3]:
W = torch.nn.Conv2d(1, 1, 2, stride=2, padding=0, bias=False)
W.weight.data = torch.tensor([[ [[1.,1.], [1.,1.]] ]], requires_grad=True)
X = torch.tensor([[ [[1,1,0,1,0,0], [0,1,0,0,1,1]] ]], dtype=torch.float)
print(str(W(X).data).replace('\n',''))

tensor([[[[3., 1., 2.]]]])



<p style="page-break-after:always;"></p>


**Multiple input channels:** $\;$ $C\,$ channels, filter $\,\mathbf{W}\;C\times f_h\times f_w,\,$ image $\,\mathbf{X}\;C\times x_h\times x_w$

$$\mathbf{Y}=\mathbf{W}\circledast\mathbf{X}=\sum\nolimits_c \mathbf{W}_{c,:,:}\circledast\mathbf{X}_{c,:,:}$$

$$\begin{bmatrix}\begin{bmatrix}1&1\\1&1\end{bmatrix},\begin{bmatrix}2&2\\2&2\end{bmatrix}\end{bmatrix}\circledast%
\begin{bmatrix}\begin{bmatrix}1&1&0\\0&1&0\\0&1&1\end{bmatrix},\begin{bmatrix}1&0&1\\1&1&1\\0&0&1\end{bmatrix}\end{bmatrix}
=\begin{bmatrix}9&8\\6&9\end{bmatrix}$$

In [4]:
W = torch.nn.Conv2d(2, 1, 2, bias=False)
W.weight.data = torch.tensor([ [ [[1.,1.],[1.,1.]], [[2.,2.],[2.,2.]] ] ], requires_grad=True)
X = torch.tensor([ [ [[1,1,0],[0,1,0],[0,1,1]], [[1,0,1],[1,1,1],[0,0,1]] ] ], dtype=torch.float)
print(str(W(X).data).replace('\n',''))

tensor([[[[9., 8.],          [6., 9.]]]])


**Multiple input and output channels:** $\;$ $C\,$ input and $\,D\,$ output, $\,\mathbf{W}\;D\times C\times f_h\times f_w,\,$ $\,\mathbf{X}\;C\times x_h\times x_w$

$$\mathbf{Y}_{d,:,:}=\mathbf{W}_{d,:,:,:}\circledast\mathbf{X}$$

$$\begin{bmatrix}\;%
\begin{bmatrix}\begin{bmatrix}1&1\\1&1\end{bmatrix},\begin{bmatrix}2&2\\2&2\end{bmatrix}\end{bmatrix},%
\begin{bmatrix}\begin{bmatrix}1&1\\1&1\end{bmatrix},\begin{bmatrix}1&1\\1&1\end{bmatrix}\end{bmatrix}\;\end{bmatrix}
\circledast%
\begin{bmatrix}\begin{bmatrix}1&1&0\\0&1&0\\0&1&1\end{bmatrix},\begin{bmatrix}1&0&1\\1&1&1\\0&0&1\end{bmatrix}\end{bmatrix}
=\begin{bmatrix}\begin{bmatrix}9&8\\6&9\end{bmatrix},\begin{bmatrix}6&5\\4&6\end{bmatrix}\end{bmatrix}$$

In [5]:
W = torch.nn.Conv2d(2, 2, 2, bias=False)
W.weight.data = torch.tensor([ [ [[1.,1.],[1.,1.]], [[2.,2.],[2.,2.]] ], 
                               [ [[1.,1.],[1.,1.]], [[1.,1.],[1.,1.]] ] ], requires_grad=True)
X = torch.tensor([ [ [[1,1,0],[0,1,0],[0,1,1]], [[1,0,1],[1,1,1],[0,0,1]] ] ], dtype=torch.float)
print(str(W(X).data).replace('\n',''))

tensor([[[[9., 8.],          [6., 9.]],         [[6., 5.],          [4., 6.]]]])


**Biases:** For each output $\,d\,$, a bias parameter $\,b_d\,$ can be added, which is summed to each element of the output.

**1x1 Convolution:** $\;$ $f_h=f_w=1\,$ to convert from $C$ to $D$ channels **point-to-point**


<p style="page-break-after:always;"></p>


**Reduction to matrix products:** $\;$ unfolding, matrix multiplication and folding

$$\mathbf{Y}=\mathbf{W}\circledast\mathbf{X}=\operatorname{Fold}(\operatorname{Unfold}(\mathbf{X})\operatorname{vec}(\mathbf{W}))$$

**Example :** $\quad\mathbf{X}=\begin{bmatrix}\begin{bmatrix}0\\1\\2\end{bmatrix}, \begin{bmatrix}3\\4\\5\end{bmatrix}\end{bmatrix}\quad%
\mathbf{W}=\begin{bmatrix}\begin{bmatrix}0\\1\end{bmatrix}, \begin{bmatrix}2\\3\end{bmatrix}\end{bmatrix}\quad%
\mathbf{Y}=\mathbf{W}\circledast\mathbf{X}=\begin{bmatrix}19\\25\end{bmatrix}$

$$\operatorname{Unfold}(\mathbf{X})=\begin{bmatrix}0&1&3&4\\1&2&4&5\end{bmatrix}\qquad%
\operatorname{vec}(\mathbf{W})=\begin{bmatrix}0&1&2&3\end{bmatrix}^t\qquad%
\operatorname{Fold}\left(\begin{bmatrix}19\\25\end{bmatrix}\right)=\begin{bmatrix}19\\25\end{bmatrix}$$

In [6]:
X = torch.tensor([[ [[0], [1], [2]], [[3], [4], [5]] ]], dtype=torch.float)
print('X =', X.shape, str(X).replace('\n','').replace(' ',''))
W = torch.nn.Conv2d(2, 1, (1, 2), bias=False)
W.weight.data = torch.tensor([ [ [[0],[1]], [[2],[3]] ] ], requires_grad=True, dtype=torch.float)
print('W =', W.weight.data.shape, str(W.weight.data).replace('\n','').replace(' ',''))
YConv2d = W(X)
print('YConv2d =', YConv2d.shape, str(YConv2d).replace('\n','').replace(' ',''))
Xu = torch.nn.functional.unfold(X, kernel_size=(2, 1)).transpose(1,2) # unfold devuelve transpuesta
print('Xu =', Xu.shape, str(Xu).replace('\n','').replace(' ',''))
vecW = W.weight.data.reshape(-1, 1)
print('vec(W) =', vecW.shape, str(vecW).replace('\n','').replace(' ',''))
Yu = Xu @ vecW
print('Yu =', Yu.shape, str(Yu).replace('\n','').replace(' ',''))
Y = torch.nn.functional.fold(Yu , (2, 1), (2, 1))
print('Y =', Y.shape, str(Y).replace('\n','').replace(' ',''))
(YConv2d - Y).abs().max().item()

X = torch.Size([1, 2, 3, 1]) tensor([[[[0.],[1.],[2.]],[[3.],[4.],[5.]]]])
W = torch.Size([1, 2, 2, 1]) tensor([[[[0.],[1.]],[[2.],[3.]]]])
YConv2d = torch.Size([1, 1, 2, 1]) tensor([[[[19.],[25.]]]],grad_fn=<ConvolutionBackward0>)
Xu = torch.Size([1, 2, 4]) tensor([[[0.,1.,3.,4.],[1.,2.,4.,5.]]])
vec(W) = torch.Size([4, 1]) tensor([[0.],[1.],[2.],[3.]])
Yu = torch.Size([1, 2, 1]) tensor([[[19.],[25.]]])
Y = torch.Size([1, 1, 2, 1]) tensor([[[[19.],[25.]]]])


0.0


<p style="page-break-after:always;"></p>
